# Generated by Django 4.2.9 on 2024-01-28 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("surename", models.CharField(max_length=50)),
                ("forname", models.CharField(max_length=50)),
                ("membership_number", models.CharField(max_length=30)),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
