name: Build Containers for Production and Push to Dockerhub
run-name: Test workflow
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  build-and-deploy-back:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./tgo-services-backend/
          push: true
          tags: 1337eddy/tgo-services-backend:latest
  
  build-and-deploy-front:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./tgo-services-frontend/
          push: true
          tags: 1337eddy/tgo-services-frontend:latest
