name: Build Containers for Production and Push to Dockerhub
run-name: Test workflow
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs: 
  build-and-deploy-back:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 1337eddy/tgo-backend/
          dockerfile: backend/Dockerfile
          tags: latest
  
  build-and-deploy-front:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 1337eddy/tgo-frontend/
          dockerfile: frontend/Dockerfile
          tags: latest
